"use client";

import React, { useState } from "react";
import { Check, Minus } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ComparisonFeature {
  name: string;
  starter: string | boolean;
  professional: string | boolean;
  enterprise: string | boolean;
}

const productFeatures: Record<string, ComparisonFeature[]> = {
  omnisphere: [
    { name: "Connected Data Feeds", starter: "Up to 3", professional: "Up to 15", enterprise: "Unlimited" },
    { name: "Generative Queries", starter: "500 / mo", professional: "5,000 / mo", enterprise: "Unlimited" },
    { name: "Autogenerated Dashboards", starter: true, professional: true, enterprise: true },
    { name: "Custom PDF Reports", starter: false, professional: true, enterprise: true },
    { name: "Dedicated Database Agent", starter: false, professional: false, enterprise: true },
    { name: "API Access Integration", starter: false, professional: "Standard", enterprise: "Ultra High Rate" },
    { name: "Support Response SLA", starter: "48 hours", professional: "12 hours", enterprise: "15 minutes" }
  ],
  cloudsentinel: [
    { name: "Connected Cloud Nodes", starter: "Up to 5", professional: "Up to 50", enterprise: "Unlimited" },
    { name: "CVE Vulnerability Scans", starter: "Weekly", professional: "Daily", enterprise: "Real-time Continuous" },
    { name: "Auto idle shutdown", starter: true, professional: true, enterprise: true },
    { name: "Multi-cloud Billing Reports", starter: false, professional: true, enterprise: true },
    { name: "Kubernetes Compliance Auditing", starter: false, professional: true, enterprise: true },
    { name: "Custom Guardrails Policies", starter: false, professional: false, enterprise: true },
    { name: "Support Response SLA", starter: "24 hours", professional: "8 hours", enterprise: "15 minutes" }
  ],
  aetherdb: [
    { name: "Global Read Latency", starter: "< 35ms", professional: "< 15ms", enterprise: "< 5ms" },
    { name: "Monthly Write Operations", starter: "1 Million", professional: "15 Million", enterprise: "Unlimited" },
    { name: "Automated Edge Caching", starter: true, professional: true, enterprise: true },
    { name: "Multi-Region Replication", starter: "1 Region", professional: "3 Regions", enterprise: "Full Global Mesh" },
    { name: "Point-In-Time recovery", starter: false, professional: "7 days retention", enterprise: "30 days retention" },
    { name: "Encrypted HSM Key storage", starter: false, professional: false, enterprise: true },
    { name: "Support Response SLA", starter: "48 hours", professional: "12 hours", enterprise: "15 minutes" }
  ]
};

export function ComparisonMatrix() {
  const [activeProduct, setActiveProduct] = useState<"omnisphere" | "cloudsentinel" | "aetherdb">("omnisphere");

  const renderValue = (value: string | boolean) => {
    if (typeof value === "boolean") {
      return value ? (
        <Check className="w-5 h-5 text-emerald-500 mx-auto" />
      ) : (
        <Minus className="w-5 h-5 text-slate-350 dark:text-slate-700 mx-auto" />
      );
    }
    return <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">{value}</span>;
  };

  return (
    <div className="w-full flex flex-col gap-8">
      {/* Product Selector Bar */}
      <div className="flex justify-center gap-2 p-1.5 bg-slate-100 dark:bg-slate-900 rounded-full max-w-md mx-auto border border-slate-200/50 dark:border-slate-800/40">
        <button
          onClick={() => setActiveProduct("omnisphere")}
          className={`flex-1 text-xs font-bold py-2.5 px-4 rounded-full transition-all duration-300 ${
            activeProduct === "omnisphere"
              ? "bg-slate-950 dark:bg-white text-white dark:text-slate-950 shadow-md"
              : "text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200"
          }`}
        >
          OmniSphere AI
        </button>
        <button
          onClick={() => setActiveProduct("cloudsentinel")}
          className={`flex-1 text-xs font-bold py-2.5 px-4 rounded-full transition-all duration-300 ${
            activeProduct === "cloudsentinel"
              ? "bg-slate-950 dark:bg-white text-white dark:text-slate-950 shadow-md"
              : "text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200"
          }`}
        >
          CloudSentinel
        </button>
        <button
          onClick={() => setActiveProduct("aetherdb")}
          className={`flex-1 text-xs font-bold py-2.5 px-4 rounded-full transition-all duration-300 ${
            activeProduct === "aetherdb"
              ? "bg-slate-950 dark:bg-white text-white dark:text-slate-950 shadow-md"
              : "text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200"
          }`}
        >
          AetherDB
        </button>
      </div>

      {/* Comparison Grid Table */}
      <div className="overflow-x-auto w-full rounded-3xl border border-slate-200/50 dark:border-slate-800/40 bg-white/60 dark:bg-slate-900/60 backdrop-blur-md shadow-xl">
        <table className="w-full min-w-[700px] border-collapse text-left">
          <thead>
            <tr className="border-b border-slate-200 dark:border-slate-800/60 bg-slate-50/50 dark:bg-slate-950/20">
              <th className="p-6 font-extrabold text-sm text-slate-900 dark:text-white w-1/3">Features Comparison</th>
              <th className="p-6 text-center w-2/9">
                <span className="block text-xs uppercase font-extrabold text-slate-400">Starter</span>
                <span className="block text-xl font-black text-slate-900 dark:text-white mt-1">Free Trial</span>
              </th>
              <th className="p-6 text-center w-2/9 border-x border-slate-200/50 dark:border-slate-850 bg-indigo-500/5">
                <span className="inline-block text-[9px] uppercase font-extrabold text-indigo-650 dark:text-indigo-400 bg-indigo-500/10 px-2 py-0.5 rounded-full mb-1">
                  Popular
                </span>
                <span className="block text-xs uppercase font-extrabold text-slate-400">Professional</span>
                <span className="block text-xl font-black text-indigo-650 dark:text-indigo-400 mt-0.5">$99 / mo</span>
              </th>
              <th className="p-6 text-center w-2/9">
                <span className="block text-xs uppercase font-extrabold text-slate-400">Enterprise</span>
                <span className="block text-xl font-black text-slate-900 dark:text-white mt-1">Custom Tier</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {productFeatures[activeProduct].map((feature, idx) => (
              <tr
                key={feature.name}
                className={`border-b last:border-0 border-slate-250/50 dark:border-slate-800/20 hover:bg-slate-50/30 dark:hover:bg-slate-900/20 transition-all ${
                  idx % 2 === 1 ? "bg-slate-50/10 dark:bg-slate-900/10" : ""
                }`}
              >
                <td className="p-6 font-bold text-slate-800 dark:text-slate-200 text-sm">{feature.name}</td>
                <td className="p-6 text-center">{renderValue(feature.starter)}</td>
                <td className="p-6 text-center border-x border-slate-200/50 dark:border-slate-850 bg-indigo-500/5">
                  {renderValue(feature.professional)}
                </td>
                <td className="p-6 text-center">{renderValue(feature.enterprise)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
